### PR TITLE
Designed new icon

### PR DESCRIPTION
**Pull request by NicKoehler**
I designed new icon, hope you like it. If you would like some changes, just tell me!

### CODE REVIEW

**Comment by NotTobi** [comment]
Thank you very much for this :)
If possible, could you make the logo in the circle a little bigger? The current logo I 'designed' is bigger and even that is barely visible.
Other than that great work, looks way better than the thing I quickly clicked together!

**Comment by NicKoehler** [comment]
logo
I made the logo a little bigger, which one do you like more? with or without gradient?

**Comment by NotTobi** [comment]
Perfect, I prefer the one without gradient.
Once you've added the changes I will complete the PR. 
Thank you for your contribution :)

**Comment by NicKoehler** [comment]
Done, glad to help 😊

**Pull request merged**
